
name: Sync Fork

on:
  schedule:
    - cron: '* */24 * * *'
  workflow_dispatch:
  
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: tgymnich/fork-sync@v1.8
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          auto_approve: true
          owner: Arasple
          base: master
          head: master
